/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jPack_Termometro;

/**
 *
 * @author rcent
 */
public class jFrame_Termometro extends javax.swing.JFrame {

    
    public jFrame_Termometro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Fondo = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Gradocelsius = new javax.swing.JLabel();
        jSlider_GradoCelcius = new javax.swing.JSlider();
        jLabel_ValorGradoCelcius = new javax.swing.JLabel();
        jLabel_GradoFarengith = new javax.swing.JLabel();
        jSlider_GradoFarengith = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_Titulo.setText(" Termometro");

        jLabel_Gradocelsius.setText("Grados Celcius");

        jSlider_GradoCelcius.setMajorTickSpacing(100);
        jSlider_GradoCelcius.setMaximum(500);
        jSlider_GradoCelcius.setMinimum(-500);
        jSlider_GradoCelcius.setMinorTickSpacing(50);
        jSlider_GradoCelcius.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider_GradoCelcius.setPaintLabels(true);
        jSlider_GradoCelcius.setPaintTicks(true);
        jSlider_GradoCelcius.setSnapToTicks(true);
        jSlider_GradoCelcius.setToolTipText("");
        jSlider_GradoCelcius.setValue(0);
        jSlider_GradoCelcius.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jSlider_GradoCelciusAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jSlider_GradoCelcius.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_GradoCelciusStateChanged(evt);
            }
        });

        jLabel_ValorGradoCelcius.setText(" ");
        jLabel_ValorGradoCelcius.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_GradoFarengith.setText("Grados Farengith");

        jSlider_GradoFarengith.setMajorTickSpacing(100);
        jSlider_GradoFarengith.setMaximum(500);
        jSlider_GradoFarengith.setMinimum(-500);
        jSlider_GradoFarengith.setMinorTickSpacing(50);
        jSlider_GradoFarengith.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider_GradoFarengith.setPaintLabels(true);
        jSlider_GradoFarengith.setPaintTicks(true);
        jSlider_GradoFarengith.setValue(0);
        jSlider_GradoFarengith.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_GradoFarengithStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel_FondoLayout = new javax.swing.GroupLayout(jPanel_Fondo);
        jPanel_Fondo.setLayout(jPanel_FondoLayout);
        jPanel_FondoLayout.setHorizontalGroup(
            jPanel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FondoLayout.createSequentialGroup()
                .addGroup(jPanel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_FondoLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_FondoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_ValorGradoCelcius, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_FondoLayout.createSequentialGroup()
                                .addGroup(jPanel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSlider_GradoCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Gradocelsius))
                                .addGroup(jPanel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_FondoLayout.createSequentialGroup()
                                        .addGap(166, 166, 166)
                                        .addComponent(jLabel_GradoFarengith)
                                        .addGap(0, 137, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_FondoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSlider_GradoFarengith, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(128, 128, 128)))))))
                .addContainerGap())
        );
        jPanel_FondoLayout.setVerticalGroup(
            jPanel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Gradocelsius)
                    .addComponent(jLabel_GradoFarengith))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSlider_GradoCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider_GradoFarengith, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel_ValorGradoCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel_Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel_Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider_GradoCelciusAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jSlider_GradoCelciusAncestorAdded
        // TODO add your handling code here:
        //jLabel_ValorGradoCelcius.setText("la temperatura en grados celcius es :"+jSlider_GradoCelcius.getValue());
    }//GEN-LAST:event_jSlider_GradoCelciusAncestorAdded

    private void jSlider_GradoCelciusStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_GradoCelciusStateChanged
        // TODO add your handling code here:
        jLabel_ValorGradoCelcius.setText("la  temperatura en grados celcius es :"+jSlider_GradoCelcius.getValue()+"y en gfarengith"+jSlider_GradoFarengith.getValue());
    }//GEN-LAST:event_jSlider_GradoCelciusStateChanged

    private void jSlider_GradoFarengithStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_GradoFarengithStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jSlider_GradoFarengithStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_Termometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_Termometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_Termometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_Termometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_Termometro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_GradoFarengith;
    private javax.swing.JLabel jLabel_Gradocelsius;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_ValorGradoCelcius;
    private javax.swing.JPanel jPanel_Fondo;
    private javax.swing.JSlider jSlider_GradoCelcius;
    private javax.swing.JSlider jSlider_GradoFarengith;
    // End of variables declaration//GEN-END:variables
}
